version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: das
      MYSQL_DATABASE: assembly
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 39
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: ./assembly
    container_name: java_app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/assembly
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: das
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    command: ["./ss.sh", "mysql:3306", "java", "-jar", "assembly.jar"]
volumes:
  mysql_data:
