# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the packaged Spring Boot application JAR file into the container
COPY target/assembly-0.0.1-SNAPSHOT.jar /app/assembly.jar

# Install MySQL server
RUN apt-get update && \
    apt-get install -y mysql-server && \
    rm -rf /var/lib/apt/lists/*

# Initialize MySQL server (replace 'yourpassword' with your desired MySQL root password)
RUN service mysql start && \
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';" && \
    mysql -e "CREATE DATABASE IF NOT EXISTS assembly;" && \
    mysql -e "GRANT ALL PRIVILEGES ON assembly.* TO 'root'@'localhost';"

# Expose the port on which the Spring Boot application will run
EXPOSE 8080

# Command to run the Spring Boot application with integrated MySQL server
CMD service mysql start && java -jar assembly.jar
